Traceback (most recent call last):
  File "/home/duanbiao2000/Documents/Mycode/GithubRepos/AutomatePython/10-debug/format_exc.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
